name: cv-demo
namespace: ${infra.kubernetes.namespace}

image: ${artifact.metadata.image}

env:
  config:
    # Override in environment with ingress controller load balancer IP or host
    ALLOWED_ORIGINS: http://13.85.192.40:8080/
